#!/usr/bin/env zsh
#*****************************************************************************************
# git-forget-file
#
# This script command will remove the named file from git history
#
# git-forget-file <path of file that should be forgotten>
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :  27-Apr-2024  9:58pm
# Modified :
#
# Copyright © 2024 By Gary Ash All rights reserved.
#*****************************************************************************************

git filter-branch --index-filter "git rm -rf --cached --ignore-unmatch $@" HEAD
rm -rf .git/refs/original/
git reflog expire --all
git gc --aggressive --prune
