#!/usr/bin/env zsh
#*****************************************************************************************
# xcode
#
# Open the Xcode workspace or project in this directory tree
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :  27-Apr-2024  9:58pm
# Modified :
#
# Copyright © 2024 By Gary Ash All rights reserved.
#*****************************************************************************************
open $(find . -name *.xcworkspace || find . -name *.xcodeproj)
